// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Data;

namespace Movies.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Movies.Data.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasWonOscar")
                        .HasColumnType("bit");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e4b647b-ed9b-480e-901d-c370c67289b0"),
                            HasWonOscar = true,
                            Rating = 7.7999999999999998,
                            Title = "Titanic",
                            Year = 1997
                        },
                        new
                        {
                            Id = new Guid("db0c28d5-4c33-4bff-9bbb-dfda6d7f245c"),
                            HasWonOscar = false,
                            Rating = 7.7999999999999998,
                            Title = "The Notebook",
                            Year = 2004
                        },
                        new
                        {
                            Id = new Guid("3c79121f-697d-4d6d-a47f-80f695f82003"),
                            HasWonOscar = true,
                            Rating = 6.7999999999999998,
                            Title = "Avatar",
                            Year = 2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
